### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by dee-y** [romankh3/raspberrypi-home-ecosystem#14]
Hello Roman, apologies for the delay in response. I will begin designing now and have some samples for you soon. Best regards.

Stephen.

**Comment by dee-y** [comment]
Here's my first draft, any suggestions or directions?

![Untitled-2-01](https://user-images.githubusercontent.com/36637989/56100845-9fb67e80-5f15-11e9-9228-76f573f36e7f.jpg)

**Comment by romankh3** [comment]
Hello, @dee-y! I am happy to see you!
What do you think about putting raspberry in the center of the "house"? 
Wi-Fi wireless shows in the roof. 
And the idea of the wires from the raspberry, like roots from the tree?

Best regards,
Roman.

**Comment by dee-y** [comment]
Hello, i made improvements below. What do you think?

![Untitled-2-01](https://user-images.githubusercontent.com/36637989/56227356-2c278500-606d-11e9-8faf-14f2b8aef045.jpg)

**Comment by romankh3** [comment]
@dee-y , hello!
I really like it!
What do you think about using `an official` image of the raspberry pi? I think it will be better for understanding that this project related to Raspberry Pi.
What do you think?

Best regards,
Roman.

**Comment by romankh3** [comment]
@dee-y, Tomorrow evening I'm going on vacation and will be available on April 30th. Don't be frustrated if I don't answer.

Best regards,
Roman.

**Comment by dee-y** [comment]
It's no problem. Will send the update you made nonetheless. Happy vacation!

**Comment by romankh3** [comment]
Hi @dee-y!
any news?

Best regards,
Roman.

**Comment by dee-y** [comment]
Apologies, in a bit.

**Comment by dee-y** [comment]
Alright here is a version with the original Raspberry Pi logo... What do you think? 
![Untitled-2-01-01](https://user-images.githubusercontent.com/36637989/57485870-b649be80-72a4-11e9-8829-4bb5d0ca7841.jpg)

**Comment by romankh3** [comment]
@dee-y, this is much better! I like it! Let's go with this pattern.

Best regards, 
Roman.

**Comment by dee-y** [comment]
Great! Will have the transparent and different versions of the logo for you soon.

**Comment by dee-y** [comment]
Transparent logo files can be downloaded here along with their editable formats in .Ai and .PSD...

https://drive.google.com/folderview?id=1KB9FtaUG9VdjF8aIu6ITk2LYumFjdm2D

Cheers!

**Comment by romankh3** [comment]
Great!
Thank you!

Best regards, Roman.

**Comment by romankh3** [comment]
@dee-y, hello!
Github added the new feature with logos - `Social preview`. It shows logos of the project in case, when you share it. It requires **1280×640px**. Can you add logo for it? 
It's a new feature)

To find it, you can go to **Settings** in the repository and find it.

Best regards,
Roman.
